<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProductsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('products')->insert(
            [
                [
                    'user_id' => 1,
                    'size_id' => 1,
                    'color_id' => 1,
                    'status_id' => 1,
                    'category_id' => 1,
                    'subcategory_id' => 1,
                    'element_id' => 1,
                    'brand_id' => 1,
                    'name' => 'Primer prenda de prueba',
                    'description' => 'Esta prenda se usará para pruebas de creación, likes y compras',
                    'price' => 150,
                    'original_price' => 350,
                    'discount' => 0,
                    'existence' => 1,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'user_id' => 1,
                    'size_id' => 2,
                    'color_id' => 2,
                    'status_id' => 2,
                    'category_id' => 2,
                    'subcategory_id' => 2,
                    'element_id' => 2,
                    'brand_id' => 2,
                    'name' => 'Segunda prenda de prueba',
                    'description' => 'Esta prenda se usará para pruebas de creación, likes y compras',
                    'price' => 150,
                    'original_price' => 350,
                    'discount' => 0,
                    'existence' => 1,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'user_id' => 1,
                    'size_id' => 3,
                    'color_id' => 3,
                    'status_id' => 3,
                    'category_id' => 3,
                    'subcategory_id' => 3,
                    'element_id' => 3,
                    'brand_id' => 3,
                    'name' => 'Tercera prenda de prueba',
                    'description' => 'Esta prenda se usará para pruebas de creación, likes y compras',
                    'price' => 150,
                    'original_price' => 350,
                    'discount' => 0,
                    'existence' => 1,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'user_id' => 1,
                    'size_id' => 4,
                    'color_id' => 4,
                    'status_id' => 4,
                    'category_id' => 4,
                    'subcategory_id' => 4,
                    'element_id' => 4,
                    'brand_id' => 4,
                    'name' => 'Cuarta prenda de prueba',
                    'description' => 'Esta prenda se usará para pruebas de creación, likes y compras',
                    'price' => 150,
                    'original_price' => 350,
                    'discount' => 0,
                    'existence' => 1,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'user_id' => 1,
                    'size_id' => 1,
                    'color_id' => 1,
                    'status_id' => 1,
                    'category_id' => 1,
                    'subcategory_id' => 1,
                    'element_id' => 1,
                    'brand_id' => 1,
                    'name' => 'Quinta prenda de prueba',
                    'description' => 'Esta prenda se usará para pruebas de creación, likes y compras',
                    'price' => 150,
                    'original_price' => 350,
                    'discount' => 0,
                    'existence' => 1,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'user_id' => 1,
                    'size_id' => 2,
                    'color_id' => 2,
                    'status_id' => 2,
                    'category_id' => 2,
                    'subcategory_id' => 2,
                    'element_id' => 2,
                    'brand_id' => 2,
                    'name' => 'Sexta prenda de prueba',
                    'description' => 'Esta prenda se usará para pruebas de creación, likes y compras',
                    'price' => 150,
                    'original_price' => 350,
                    'discount' => 0,
                    'existence' => 1,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'user_id' => 1,
                    'size_id' => 3,
                    'color_id' => 3,
                    'status_id' => 3,
                    'category_id' => 3,
                    'subcategory_id' => 3,
                    'element_id' => 3,
                    'brand_id' => 3,
                    'name' => 'Septima prenda de prueba',
                    'description' => 'Esta prenda se usará para pruebas de creación, likes y compras',
                    'price' => 150,
                    'original_price' => 350,
                    'discount' => 0,
                    'existence' => 1,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'user_id' => 1,
                    'size_id' => 4,
                    'color_id' => 4,
                    'status_id' => 4,
                    'category_id' => 4,
                    'subcategory_id' => 4,
                    'element_id' => 4,
                    'brand_id' => 4,
                    'name' => 'Octava prenda de prueba',
                    'description' => 'Esta prenda se usará para pruebas de creación, likes y compras',
                    'price' => 150,
                    'original_price' => 350,
                    'discount' => 0,
                    'existence' => 1,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'user_id' => 1,
                    'size_id' => 1,
                    'color_id' => 1,
                    'status_id' => 1,
                    'category_id' => 1,
                    'subcategory_id' => 1,
                    'element_id' => 1,
                    'brand_id' => 1,
                    'name' => 'Novena prenda de prueba',
                    'description' => 'Esta prenda se usará para pruebas de creación, likes y compras',
                    'price' => 150,
                    'original_price' => 350,
                    'discount' => 0,
                    'existence' => 1,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'user_id' => 1,
                    'size_id' => 2,
                    'color_id' => 2,
                    'status_id' => 2,
                    'category_id' => 2,
                    'subcategory_id' => 2,
                    'element_id' => 2,
                    'brand_id' => 2,
                    'name' => 'Décima prenda de prueba',
                    'description' => 'Esta prenda se usará para pruebas de creación, likes y compras',
                    'price' => 150,
                    'original_price' => 350,
                    'discount' => 0,
                    'existence' => 1,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'user_id' => 1,
                    'size_id' => 3,
                    'color_id' => 3,
                    'status_id' => 3,
                    'category_id' => 3,
                    'subcategory_id' => 3,
                    'element_id' => 3,
                    'brand_id' => 3,
                    'name' => 'Décima primera prenda de prueba',
                    'description' => 'Esta prenda se usará para pruebas de creación, likes y compras',
                    'price' => 150,
                    'original_price' => 350,
                    'discount' => 0,
                    'existence' => 1,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'user_id' => 1,
                    'size_id' => 4,
                    'color_id' => 4,
                    'status_id' => 4,
                    'category_id' => 4,
                    'subcategory_id' => 4,
                    'element_id' => 4,
                    'brand_id' => 4,
                    'name' => 'Décima segunda prenda de prueba',
                    'description' => 'Esta prenda se usará para pruebas de creación, likes y compras',
                    'price' => 150,
                    'original_price' => 350,
                    'discount' => 0,
                    'existence' => 1,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'user_id' => 1,
                    'size_id' => 1,
                    'color_id' => 1,
                    'status_id' => 1,
                    'category_id' => 1,
                    'subcategory_id' => 1,
                    'element_id' => 1,
                    'brand_id' => 1,
                    'name' => 'Décima tercera prenda de prueba',
                    'description' => 'Esta prenda se usará para pruebas de creación, likes y compras',
                    'price' => 150,
                    'original_price' => 350,
                    'discount' => 0,
                    'existence' => 1,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'user_id' => 1,
                    'size_id' => 2,
                    'color_id' => 2,
                    'status_id' => 2,
                    'category_id' => 2,
                    'subcategory_id' => 2,
                    'element_id' => 2,
                    'brand_id' => 2,
                    'name' => 'Décima cuarta prenda de prueba',
                    'description' => 'Esta prenda se usará para pruebas de creación, likes y compras',
                    'price' => 150,
                    'original_price' => 350,
                    'discount' => 0,
                    'existence' => 1,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'user_id' => 1,
                    'size_id' => 3,
                    'color_id' => 3,
                    'status_id' => 3,
                    'category_id' => 3,
                    'subcategory_id' => 3,
                    'element_id' => 3,
                    'brand_id' => 3,
                    'name' => 'Décima quinta prenda de prueba',
                    'description' => 'Esta prenda se usará para pruebas de creación, likes y compras',
                    'price' => 150,
                    'original_price' => 350,
                    'discount' => 0,
                    'existence' => 1,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'user_id' => 1,
                    'size_id' => 4,
                    'color_id' => 4,
                    'status_id' => 4,
                    'category_id' => 4,
                    'subcategory_id' => 4,
                    'element_id' => 4,
                    'brand_id' => 4,
                    'name' => 'Décima sexta prenda de prueba',
                    'description' => 'Esta prenda se usará para pruebas de creación, likes y compras',
                    'price' => 150,
                    'original_price' => 350,
                    'discount' => 0,
                    'existence' => 1,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'user_id' => 1,
                    'size_id' => 1,
                    'color_id' => 1,
                    'status_id' => 1,
                    'category_id' => 1,
                    'subcategory_id' => 1,
                    'element_id' => 1,
                    'brand_id' => 1,
                    'name' => 'Décima septima prenda de prueba',
                    'description' => 'Esta prenda se usará para pruebas de creación, likes y compras',
                    'price' => 150,
                    'original_price' => 350,
                    'discount' => 0,
                    'existence' => 1,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'user_id' => 1,
                    'size_id' => 2,
                    'color_id' => 2,
                    'status_id' => 2,
                    'category_id' => 2,
                    'subcategory_id' => 2,
                    'element_id' => 2,
                    'brand_id' => 2,
                    'name' => 'Décima octava prenda de prueba',
                    'description' => 'Esta prenda se usará para pruebas de creación, likes y compras',
                    'price' => 150,
                    'original_price' => 350,
                    'discount' => 0,
                    'existence' => 1,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'user_id' => 1,
                    'size_id' => 3,
                    'color_id' => 3,
                    'status_id' => 3,
                    'category_id' => 3,
                    'subcategory_id' => 3,
                    'element_id' => 3,
                    'brand_id' => 3,
                    'name' => 'Décima novena prenda de prueba',
                    'description' => 'Esta prenda se usará para pruebas de creación, likes y compras',
                    'price' => 150,
                    'original_price' => 350,
                    'discount' => 0,
                    'existence' => 1,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'user_id' => 1,
                    'size_id' => 4,
                    'color_id' => 4,
                    'status_id' => 4,
                    'category_id' => 4,
                    'subcategory_id' => 4,
                    'element_id' => 4,
                    'brand_id' => 4,
                    'name' => 'Vigésima prenda de prueba',
                    'description' => 'Esta prenda se usará para pruebas de creación, likes y compras',
                    'price' => 150,
                    'original_price' => 350,
                    'discount' => 0,
                    'existence' => 1,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
            ]
        );
    }
}
