<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class SubcategoriesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('subcategories')->insert(
            [
                [
                    'user_id' => 1,
                    'category_id' => 1,
                    'name' => 'Abrigos',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'user_id' => 1,
                    'category_id' => 1,
                    'name' => 'Blusas',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'user_id' => 1,
                    'category_id' => 1,
                    'name' => 'Conjuntos',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'user_id' => 1,
                    'category_id' => 1,
                    'name' => 'Chamarra',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'user_id' => 1,
                    'category_id' => 1,
                    'name' => 'Faldas',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'user_id' => 1,
                    'category_id' => 1,
                    'name' => 'Jeans',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'user_id' => 1,
                    'category_id' => 1,
                    'name' => 'Pants',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'user_id' => 1,
                    'category_id' => 1,
                    'name' => 'Pantalones',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'user_id' => 1,
                    'category_id' => 1,
                    'name' => 'Pijamas',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'user_id' => 1,
                    'category_id' => 1,
                    'name' => 'Playeras',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'user_id' => 1,
                    'category_id' => 1,
                    'name' => 'Ropa Deportiva',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'user_id' => 1,
                    'category_id' => 1,
                    'name' => 'Short',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'user_id' => 1,
                    'category_id' => 1,
                    'name' => 'Suéter',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'user_id' => 1,
                    'category_id' => 1,
                    'name' => 'Tenis',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'user_id' => 1,
                    'category_id' => 1,
                    'name' => 'Vestidos',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'user_id' => 1,
                    'category_id' => 1,
                    'name' => 'Zapatos',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'user_id' => 1,
                    'category_id' => 1,
                    'name' => 'Accesorios',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'user_id' => 1,
                    'category_id' => 2,
                    'name' => 'Suéter',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'user_id' => 1,
                    'category_id' => 2,
                    'name' => 'Chamarra',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'user_id' => 1,
                    'category_id' => 2,
                    'name' => 'Abrigo',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'user_id' => 1,
                    'category_id' => 2,
                    'name' => 'Pantalón de vestir',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'user_id' => 1,
                    'category_id' => 2,
                    'name' => 'Jeans',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'user_id' => 1,
                    'category_id' => 2,
                    'name' => 'Traje sastre',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'user_id' => 1,
                    'category_id' => 2,
                    'name' => 'Camisas',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'user_id' => 1,
                    'category_id' => 2,
                    'name' => 'Ropa deportiva',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'user_id' => 1,
                    'category_id' => 2,
                    'name' => 'Zapatos',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'user_id' => 1,
                    'category_id' => 2,
                    'name' => 'Tenis',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'user_id' => 1,
                    'category_id' => 2,
                    'name' => 'Accesorios',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'user_id' => 1,
                    'category_id' => 3,
                    'name' => 'Vestidos',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'user_id' => 1,
                    'category_id' => 3,
                    'name' => 'Blusas',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'user_id' => 1,
                    'category_id' => 3,
                    'name' => 'Conjuntos',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'user_id' => 1,
                    'category_id' => 3,
                    'name' => 'Faldas',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'user_id' => 1,
                    'category_id' => 3,
                    'name' => 'Pantalones',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'user_id' => 1,
                    'category_id' => 3,
                    'name' => 'Pants',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'user_id' => 1,
                    'category_id' => 3,
                    'name' => 'Jeans',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'user_id' => 1,
                    'category_id' => 3,
                    'name' => 'Pijamas',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'user_id' => 1,
                    'category_id' => 3,
                    'name' => 'Playeras',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'user_id' => 1,
                    'category_id' => 3,
                    'name' => 'Ropa Deportiva',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'user_id' => 1,
                    'category_id' => 3,
                    'name' => 'Short',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'user_id' => 1,
                    'category_id' => 3,
                    'name' => 'Suéter',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'user_id' => 1,
                    'category_id' => 3,
                    'name' => 'Tenis',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'user_id' => 1,
                    'category_id' => 3,
                    'name' => 'Vestidos',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'user_id' => 1,
                    'category_id' => 3,
                    'name' => 'Zapatos',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'user_id' => 1,
                    'category_id' => 3,
                    'name' => 'Accesorios',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'user_id' => 1,
                    'category_id' => 3,
                    'name' => 'Accesorios',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'user_id' => 1,
                    'category_id' => 4,
                    'name' => 'Abrigo',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'user_id' => 1,
                    'category_id' => 4,
                    'name' => 'Bermudas',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'user_id' => 1,
                    'category_id' => 4,
                    'name' => 'Camisas',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'user_id' => 1,
                    'category_id' => 4,
                    'name' => 'Chamarra',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'user_id' => 1,
                    'category_id' => 4,
                    'name' => 'Jeans',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'user_id' => 1,
                    'category_id' => 4,
                    'name' => 'Pantalón vestir',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'user_id' => 1,
                    'category_id' => 4,
                    'name' => 'Pants',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'user_id' => 1,
                    'category_id' => 4,
                    'name' => 'Pijamás',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'user_id' => 1,
                    'category_id' => 4,
                    'name' => 'Playeras',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'user_id' => 1,
                    'category_id' => 4,
                    'name' => 'Ropa deportiva',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'user_id' => 1,
                    'category_id' => 4,
                    'name' => 'Suéter',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'user_id' => 1,
                    'category_id' => 4,
                    'name' => 'Shorts',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'user_id' => 1,
                    'category_id' => 4,
                    'name' => 'Traje de vestir',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'user_id' => 1,
                    'category_id' => 4,
                    'name' => 'Tenis',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'user_id' => 1,
                    'category_id' => 4,
                    'name' => 'Zapatos',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'user_id' => 1,
                    'category_id' => 4,
                    'name' => 'Accesorios',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'user_id' => 1,
                    'category_id' => 5,
                    'name' => 'Conjunto',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'user_id' => 1,
                    'category_id' => 5,
                    'name' => 'Falda',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'user_id' => 1,
                    'category_id' => 5,
                    'name' => 'Mameluco',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'user_id' => 1,
                    'category_id' => 5,
                    'name' => 'Playera',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'user_id' => 1,
                    'category_id' => 5,
                    'name' => 'Pantalón',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'user_id' => 1,
                    'category_id' => 5,
                    'name' => 'Vestido',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'user_id' => 1,
                    'category_id' => 5,
                    'name' => 'Accesorios',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
            ],
        );
    }
}
